In [1]:
# Instalamos numpy en nuetra máquina de Google Colab
!pip install numpy

In [2]:
import numpy as np

# 1. Create

In [10]:
# Iniciar un arreglo de numpy con datos aleatorios (Utilizamos las dimensiones del arreglo)
data = np.random.rand(4,3,4)

# Iniciar un arreglo de numpy lleno de 0's (Utilizamos una tupla con las dimensiones del arreglo)
zeroes = np.zeros((2,2,2))

# Iniciar un arreglo de numpy lleno con el número 7 (Utilizamos una tupla con las dimensiones del arreglo y el dato que queremos en el arreglo)
full = np.full((2,2,2), 7)

# Iniciar un arreglo de numpy lleno de 1's (Utilizamos una tupla con las dimensiones del arreglo)
ones = np.ones((2,2,2))

In [4]:
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [7]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [11]:
data

array([[[0.74086848, 0.94867709, 0.45990253, 0.64822005],
        [0.57720018, 0.268263  , 0.64890715, 0.20219393],
        [0.27935776, 0.22248415, 0.51653968, 0.8152122 ]],

       [[0.19198953, 0.79131252, 0.91706172, 0.04670133],
        [0.26184326, 0.8183341 , 0.76265297, 0.60007497],
        [0.93443657, 0.30671029, 0.09625724, 0.00523162]],

       [[0.89630622, 0.11882523, 0.46186596, 0.94260158],
        [0.33195822, 0.31978871, 0.09370446, 0.0844914 ],
        [0.84263637, 0.9666617 , 0.64298207, 0.07669688]],

       [[0.59967562, 0.43684605, 0.6929089 , 0.05077993],
        [0.9867454 , 0.47337857, 0.69432697, 0.20265485],
        [0.92255282, 0.11538312, 0.2862353 , 0.78495581]]])

In [12]:
# Iniciar un arreglo de numpy con una lista de python
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [13]:
# El tipo de dato NO ES UNA LISTA DE PYTHON
type(arr)

numpy.ndarray

In [14]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 2. Read

In [15]:
# Atributos de un arreglo de numpy
shape = data.shape
size = data.size
types = data.dtype

In [16]:
types

dtype('float64')

In [17]:
size

48

In [18]:
shape

(4, 3, 4)

In [19]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [20]:
singleval

0.7408684835458267

In [21]:
data

array([[[0.74086848, 0.94867709, 0.45990253, 0.64822005],
        [0.57720018, 0.268263  , 0.64890715, 0.20219393],
        [0.27935776, 0.22248415, 0.51653968, 0.8152122 ]],

       [[0.19198953, 0.79131252, 0.91706172, 0.04670133],
        [0.26184326, 0.8183341 , 0.76265297, 0.60007497],
        [0.93443657, 0.30671029, 0.09625724, 0.00523162]],

       [[0.89630622, 0.11882523, 0.46186596, 0.94260158],
        [0.33195822, 0.31978871, 0.09370446, 0.0844914 ],
        [0.84263637, 0.9666617 , 0.64298207, 0.07669688]],

       [[0.59967562, 0.43684605, 0.6929089 , 0.05077993],
        [0.9867454 , 0.47337857, 0.69432697, 0.20265485],
        [0.92255282, 0.11538312, 0.2862353 , 0.78495581]]])

# 3. Update

In [22]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [23]:
list2

array([0.26681212, 0.13031085, 0.55279745, 0.90714584, 0.61608202,
       0.46313402, 0.35709515, 0.1059009 , 0.62624447, 0.29363518])

In [24]:
# Operaciones matemáticas en los arreglos
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
# Producto punto IMPORTANTE PARA EL PROYECTO 1
dot = np.dot(list1, list2)

In [29]:
dot

2.870256110287113

In [25]:
add

array([0.90749611, 0.65358519, 1.50964388, 1.61221715, 1.46114067,
       0.68560121, 1.11299133, 0.50644411, 1.24598622, 0.76520198])

In [26]:
sub

array([ 0.37387187,  0.39296349,  0.40404897, -0.20207452,  0.22897662,
       -0.24066683,  0.39880103,  0.29464231, -0.00650272,  0.17793163])

In [27]:
div

array([2.40125521, 4.01558538, 1.73091685, 0.77724142, 1.3716658 ,
       0.48035165, 2.11679205, 3.7822455 , 0.98961633, 1.60596154])

In [28]:
mult

array([0.17094225, 0.06818832, 0.52894227, 0.63960251, 0.52062544,
       0.10303212, 0.26992686, 0.04241789, 0.38810984, 0.1384686 ])

In [30]:
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [31]:
maxs

0.9568464271799163

In [32]:
data

array([[[0.74086848, 0.94867709, 0.45990253, 0.64822005],
        [0.57720018, 0.268263  , 0.64890715, 0.20219393],
        [0.27935776, 0.22248415, 0.51653968, 0.8152122 ]],

       [[0.19198953, 0.79131252, 0.91706172, 0.04670133],
        [0.26184326, 0.8183341 , 0.76265297, 0.60007497],
        [0.93443657, 0.30671029, 0.09625724, 0.00523162]],

       [[0.89630622, 0.11882523, 0.46186596, 0.94260158],
        [0.33195822, 0.31978871, 0.09370446, 0.0844914 ],
        [0.84263637, 0.9666617 , 0.64298207, 0.07669688]],

       [[0.59967562, 0.43684605, 0.6929089 , 0.05077993],
        [0.9867454 , 0.47337857, 0.69432697, 0.20265485],
        [0.92255282, 0.11538312, 0.2862353 , 0.78495581]]])

In [33]:
# Asignar un nuevo valor a un elemento del arreglo OJO! TENEMOS MULTIPLES DIMENSIONES
data[0][0][0] = 700

In [34]:
data

array([[[7.00000000e+02, 9.48677094e-01, 4.59902535e-01, 6.48220051e-01],
        [5.77200178e-01, 2.68262999e-01, 6.48907148e-01, 2.02193926e-01],
        [2.79357759e-01, 2.22484150e-01, 5.16539683e-01, 8.15212199e-01]],

       [[1.91989531e-01, 7.91312518e-01, 9.17061724e-01, 4.67013342e-02],
        [2.61843259e-01, 8.18334103e-01, 7.62652965e-01, 6.00074969e-01],
        [9.34436572e-01, 3.06710294e-01, 9.62572418e-02, 5.23161932e-03]],

       [[8.96306219e-01, 1.18825233e-01, 4.61865957e-01, 9.42601584e-01],
        [3.31958216e-01, 3.19788708e-01, 9.37044576e-02, 8.44913980e-02],
        [8.42636369e-01, 9.66661695e-01, 6.42982072e-01, 7.66968809e-02]],

       [[5.99675620e-01, 4.36846054e-01, 6.92908898e-01, 5.07799281e-02],
        [9.86745396e-01, 4.73378568e-01, 6.94326969e-01, 2.02654848e-01],
        [9.22552824e-01, 1.15383125e-01, 2.86235304e-01, 7.84955810e-01]]])

In [35]:
data.sort()
data

array([[[4.59902535e-01, 6.48220051e-01, 9.48677094e-01, 7.00000000e+02],
        [2.02193926e-01, 2.68262999e-01, 5.77200178e-01, 6.48907148e-01],
        [2.22484150e-01, 2.79357759e-01, 5.16539683e-01, 8.15212199e-01]],

       [[4.67013342e-02, 1.91989531e-01, 7.91312518e-01, 9.17061724e-01],
        [2.61843259e-01, 6.00074969e-01, 7.62652965e-01, 8.18334103e-01],
        [5.23161932e-03, 9.62572418e-02, 3.06710294e-01, 9.34436572e-01]],

       [[1.18825233e-01, 4.61865957e-01, 8.96306219e-01, 9.42601584e-01],
        [8.44913980e-02, 9.37044576e-02, 3.19788708e-01, 3.31958216e-01],
        [7.66968809e-02, 6.42982072e-01, 8.42636369e-01, 9.66661695e-01]],

       [[5.07799281e-02, 4.36846054e-01, 5.99675620e-01, 6.92908898e-01],
        [2.02654848e-01, 4.73378568e-01, 6.94326969e-01, 9.86745396e-01],
        [1.15383125e-01, 2.86235304e-01, 7.84955810e-01, 9.22552824e-01]]])

In [36]:
print(data.shape)

(4, 3, 4)


In [37]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 12)

In [38]:
data

array([[[4.59902535e-01, 6.48220051e-01, 9.48677094e-01, 7.00000000e+02,
         2.02193926e-01, 2.68262999e-01, 5.77200178e-01, 6.48907148e-01,
         2.22484150e-01, 2.79357759e-01, 5.16539683e-01, 8.15212199e-01],
        [4.67013342e-02, 1.91989531e-01, 7.91312518e-01, 9.17061724e-01,
         2.61843259e-01, 6.00074969e-01, 7.62652965e-01, 8.18334103e-01,
         5.23161932e-03, 9.62572418e-02, 3.06710294e-01, 9.34436572e-01]],

       [[1.18825233e-01, 4.61865957e-01, 8.96306219e-01, 9.42601584e-01,
         8.44913980e-02, 9.37044576e-02, 3.19788708e-01, 3.31958216e-01,
         7.66968809e-02, 6.42982072e-01, 8.42636369e-01, 9.66661695e-01],
        [5.07799281e-02, 4.36846054e-01, 5.99675620e-01, 6.92908898e-01,
         2.02654848e-01, 4.73378568e-01, 6.94326969e-01, 9.86745396e-01,
         1.15383125e-01, 2.86235304e-01, 7.84955810e-01, 9.22552824e-01]]])

In [39]:
# Concatenar arreglos
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [40]:
# En la posición 2 del arreglo zeroes quiero insertar el número 1
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [41]:
data

array([[[4.59902535e-01, 6.48220051e-01, 9.48677094e-01, 7.00000000e+02,
         2.02193926e-01, 2.68262999e-01, 5.77200178e-01, 6.48907148e-01,
         2.22484150e-01, 2.79357759e-01, 5.16539683e-01, 8.15212199e-01],
        [4.67013342e-02, 1.91989531e-01, 7.91312518e-01, 9.17061724e-01,
         2.61843259e-01, 6.00074969e-01, 7.62652965e-01, 8.18334103e-01,
         5.23161932e-03, 9.62572418e-02, 3.06710294e-01, 9.34436572e-01]],

       [[1.18825233e-01, 4.61865957e-01, 8.96306219e-01, 9.42601584e-01,
         8.44913980e-02, 9.37044576e-02, 3.19788708e-01, 3.31958216e-01,
         7.66968809e-02, 6.42982072e-01, 8.42636369e-01, 9.66661695e-01],
        [5.07799281e-02, 4.36846054e-01, 5.99675620e-01, 6.92908898e-01,
         2.02654848e-01, 4.73378568e-01, 6.94326969e-01, 9.86745396e-01,
         1.15383125e-01, 2.86235304e-01, 7.84955810e-01, 9.22552824e-01]]])

In [42]:
np.delete(data, 0, axis=1)

array([[[0.04670133, 0.19198953, 0.79131252, 0.91706172, 0.26184326,
         0.60007497, 0.76265297, 0.8183341 , 0.00523162, 0.09625724,
         0.30671029, 0.93443657]],

       [[0.05077993, 0.43684605, 0.59967562, 0.6929089 , 0.20265485,
         0.47337857, 0.69432697, 0.9867454 , 0.11538312, 0.2862353 ,
         0.78495581, 0.92255282]]])

In [43]:
np.save("new array", data)

In [44]:
test = np.load("new array.npy")

In [45]:
test

array([[[4.59902535e-01, 6.48220051e-01, 9.48677094e-01, 7.00000000e+02,
         2.02193926e-01, 2.68262999e-01, 5.77200178e-01, 6.48907148e-01,
         2.22484150e-01, 2.79357759e-01, 5.16539683e-01, 8.15212199e-01],
        [4.67013342e-02, 1.91989531e-01, 7.91312518e-01, 9.17061724e-01,
         2.61843259e-01, 6.00074969e-01, 7.62652965e-01, 8.18334103e-01,
         5.23161932e-03, 9.62572418e-02, 3.06710294e-01, 9.34436572e-01]],

       [[1.18825233e-01, 4.61865957e-01, 8.96306219e-01, 9.42601584e-01,
         8.44913980e-02, 9.37044576e-02, 3.19788708e-01, 3.31958216e-01,
         7.66968809e-02, 6.42982072e-01, 8.42636369e-01, 9.66661695e-01],
        [5.07799281e-02, 4.36846054e-01, 5.99675620e-01, 6.92908898e-01,
         2.02654848e-01, 4.73378568e-01, 6.94326969e-01, 9.86745396e-01,
         1.15383125e-01, 2.86235304e-01, 7.84955810e-01, 9.22552824e-01]]])